
language:
  - php

dist:
  - trusty

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: PHP53=true
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
      env: HHVM=true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install
  - if [[ $PHP53 == true ]]; then composer require "phpunit/phpunit:5.7"; fi
  - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

script:
  - vendor/bin/phpcs --config-set installed_paths "../../wp-coding-standards/wpcs/,../../automattic/phpcs-neutron-standard/,../../inpsyde/php-coding-standards/,../../wimg/php-compatibility/,../../pheromone/phpcs-security-audit/Security/"
  - vendor/bin/phpcs -n
